repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: debug-statements
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-json
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: end-of-file-fixer

- repo: local
  hooks:
  - id: check-datetime-now
    name: check_datetime_now
    description: Prefer datetime.utcnow()
    language: pygrep
    entry: 'datetime\.now\(\)'
    types: [python]

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      args: ['--exclude=docs/*,*migrations*', '--ignore=E501,W503,E203']

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
      additional_dependencies: ['toml']

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
    - id: python-check-mock-methods

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
